version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  matrix-tests:
    jobs:
      - build:
          - steps:
              - run: npm install
      - node/test:
          matrix:
            parameters:
              version:
                - 13.11.0
                - 12.16.0
                - 10.19.0
